# Generated by Django 5.2.4 on 2026-09-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active_delegate', models.BooleanField(default=True, verbose_name='Délégué actif')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegates', to='specialties.specialty', verbose_name='Spécialité restreinte (vide = toutes)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Délégué',
                'verbose_name_plural': 'Profils Délégués',
            },
        ),
    ]
