# Generated by Django 5.2.4 on 2026-09-29 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet du Master')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code acronyme (ex: SSI, BIGDATA)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('accent_color', models.CharField(default='#3b82f6', max_length=30, verbose_name="Couleur d'accent (Hex / Theme token)")),
                ('icon_name', models.CharField(default='BookOpen', max_length=50, verbose_name="Nom de l'icône")),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('code', models.CharField(max_length=30, verbose_name='Code du module')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé du module')),
                ('semester', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4')], default='S1', max_length=2, verbose_name='Semestre')),
                ('coefficient', models.PositiveSmallIntegerField(default=3, verbose_name='Coefficient')),
                ('description', models.TextField(blank=True, verbose_name='Description / Objectifs')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='specialties.specialty', verbose_name='Spécialité associée')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['semester', 'code'],
                'unique_together': {('specialty', 'code')},
            },
        ),
    ]
