# Generated by Django 5.2.4 on 2026-09-29 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('resource_type', models.CharField(choices=[('DRIVE', 'Google Drive'), ('YOUTUBE', 'Vidéo YouTube')], default='DRIVE', max_length=10, verbose_name='Type de ressource')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la ressource')),
                ('url', models.URLField(max_length=500, verbose_name='Lien direct URL')),
                ('description', models.TextField(blank=True, verbose_name='Description / Remarques')),
                ('contributor_name', models.CharField(blank=True, max_length=100, verbose_name="Nom ou pseudo de l'étudiant")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='specialties.module', verbose_name='Module visé')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='specialties.specialty', verbose_name='Spécialité visée')),
            ],
            options={
                'verbose_name': 'Contribution étudiante',
                'verbose_name_plural': 'Contributions étudiantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriveResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('category', models.CharField(choices=[('COURS', 'Cours Magistral'), ('TD', 'Travaux Dirigés (TD)'), ('TP', 'Travaux Pratiques (TP)'), ('EXAM', 'Examens & Corrigés'), ('SUMMARY', 'Fiches & Résumés')], default='COURS', max_length=15, verbose_name='Catégorie')),
                ('drive_url', models.URLField(max_length=500, verbose_name='Lien Google Drive')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de consultations')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Vérifié par un modérateur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_resources', to='specialties.module', verbose_name='Module associé')),
            ],
            options={
                'verbose_name': 'Ressource Google Drive',
                'verbose_name_plural': 'Ressources Google Drive',
                'ordering': ['category', '-views_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la vidéo')),
                ('youtube_url', models.URLField(max_length=500, verbose_name='Lien de la vidéo / playlist YouTube')),
                ('video_id', models.CharField(blank=True, max_length=50, verbose_name='ID YouTube (ex: dQw4w9WgXcQ)')),
                ('channel_name', models.CharField(blank=True, max_length=120, verbose_name='Nom de la chaîne')),
                ('playlist_name', models.CharField(blank=True, max_length=150, verbose_name='Nom de la playlist')),
                ('duration', models.CharField(blank=True, max_length=30, verbose_name='Durée estimée')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Vérifié par un modérateur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_resources', to='specialties.module', verbose_name='Module associé')),
            ],
            options={
                'verbose_name': 'Ressource YouTube',
                'verbose_name_plural': 'Ressources YouTube',
                'ordering': ['-created_at'],
            },
        ),
    ]
