# Generated by Django 5.2.4 on 2026-09-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveresource',
            name='module',
        ),
        migrations.RemoveField(
            model_name='youtuberesource',
            name='module',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('resource_type', models.CharField(choices=[('DRIVE', 'Google Drive'), ('YOUTUBE', 'Vidéo YouTube')], default='DRIVE', max_length=10, verbose_name='Type de ressource')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document ou de la vidéo')),
                ('url', models.URLField(max_length=500, verbose_name='Lien direct (Drive ou YouTube)')),
                ('category', models.CharField(blank=True, choices=[('COURS', 'Cours Magistral'), ('TD', 'Travaux Dirigés (TD)'), ('TP', 'Travaux Pratiques (TP)'), ('EXAM', 'Examens & Corrigés'), ('SUMMARY', 'Fiches & Résumés')], default='COURS', max_length=15, verbose_name='Catégorie (Drive)')),
                ('channel_name', models.CharField(blank=True, max_length=120, verbose_name='Nom de la chaîne (YouTube)')),
                ('duration', models.CharField(blank=True, max_length=30, verbose_name='Durée (YouTube)')),
                ('contributor_name', models.CharField(blank=True, default='Étudiant Anonyme', max_length=100, verbose_name='Auteur de la proposition')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], db_index=True, default='pending', max_length=10, verbose_name='Statut de validation')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de refus (optionnel)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues / Téléchargements')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='specialties.module', verbose_name='Module associé')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_resources', to=settings.AUTH_USER_MODEL, verbose_name='Délégué validateur')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='DriveResource',
        ),
        migrations.DeleteModel(
            name='YouTubeResource',
        ),
    ]
