import {
  ShieldAlert,
  BrainCircuit,
  Code2,
  Cpu,
  Database,
  Dna,
  Network
} from 'lucide-react';

export const SPECIALTY_THEMES = {
  ssi: {
    code: 'SSI',
    name: 'Sécurité des Systèmes Informatiques',
    slug: 'ssi',
    color: '#10B981',
    icon: ShieldAlert,
    tagline: 'Cyberdéfense, Cryptographie & Pentesting',
    badgeClass: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    borderHover: 'hover:border-emerald-500/50',
    glowClass: 'from-emerald-500/20 via-transparent to-transparent',
    gradientText: 'from-emerald-400 to-teal-200',
    accentBg: 'bg-emerald-500',
  },
  sii: {
    code: 'SII',
    name: "Systèmes d'Information Intelligents",
    slug: 'sii',
    color: '#8B5CF6',
    icon: BrainCircuit,
    tagline: 'Intelligence Artificielle & Sémantique',
    badgeClass: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    borderHover: 'hover:border-purple-500/50',
    glowClass: 'from-purple-500/20 via-transparent to-transparent',
    gradientText: 'from-purple-400 to-indigo-200',
    accentBg: 'bg-purple-500',
  },
  il: {
    code: 'IL',
    name: 'Ingénierie du Logiciel',
    slug: 'il',
    color: '#F59E0B',
    icon: Code2,
    tagline: 'Architectures Cloud, DevOps & Clean Code',
    badgeClass: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
    borderHover: 'hover:border-amber-500/50',
    glowClass: 'from-amber-500/20 via-transparent to-transparent',
    gradientText: 'from-amber-400 to-yellow-200',
    accentBg: 'bg-amber-500',
  },
  'm1-hpc': {
    code: 'M1 HPC',
    name: 'High Performance Computing',
    slug: 'm1-hpc',
    color: '#F43F5E',
    icon: Cpu,
    tagline: 'Calcul Haute Performance, GPU & Parallélisme',
    badgeClass: 'bg-rose-500/10 text-rose-400 border-rose-500/30',
    borderHover: 'hover:border-rose-500/50',
    glowClass: 'from-rose-500/20 via-transparent to-transparent',
    gradientText: 'from-rose-400 to-pink-200',
    accentBg: 'bg-rose-500',
  },
  bigdata: {
    code: 'BIGDATA',
    name: 'Big Data et Analytics',
    slug: 'bigdata',
    color: '#0EA5E9',
    icon: Database,
    tagline: 'Ingénierie Big Data, Spark & Streaming',
    badgeClass: 'bg-sky-500/10 text-sky-400 border-sky-500/30',
    borderHover: 'hover:border-sky-500/50',
    glowClass: 'from-sky-500/20 via-transparent to-transparent',
    gradientText: 'from-sky-400 to-cyan-200',
    accentBg: 'bg-sky-500',
  },
  bioinfo: {
    code: 'BIOINFO',
    name: 'Bioinformatique',
    slug: 'bioinfo',
    color: '#14B8A6',
    icon: Dna,
    tagline: 'Génomique Numérique & Biostatistiques',
    badgeClass: 'bg-teal-500/10 text-teal-400 border-teal-500/30',
    borderHover: 'hover:border-teal-500/50',
    glowClass: 'from-teal-500/20 via-transparent to-transparent',
    gradientText: 'from-teal-400 to-emerald-200',
    accentBg: 'bg-teal-500',
  },
  rsd: {
    code: 'RSD',
    name: 'Réseaux et Systèmes Distribués',
    slug: 'rsd',
    color: '#D946EF',
    icon: Network,
    tagline: 'Architectures Réseaux, 5G/6G & SDN',
    badgeClass: 'bg-fuchsia-500/10 text-fuchsia-400 border-fuchsia-500/30',
    borderHover: 'hover:border-fuchsia-500/50',
    glowClass: 'from-fuchsia-500/20 via-transparent to-transparent',
    gradientText: 'from-fuchsia-400 to-purple-200',
    accentBg: 'bg-fuchsia-500',
  },
};

export const getSpecialtyTheme = (slug) => {
  return SPECIALTY_THEMES[slug?.toLowerCase()] || SPECIALTY_THEMES.ssi;
};
